### ISSUE TITLE
Incorrect ajax calls when installed in subfolder

### ISSUE THREAD

**Issue by hamacekh** [mantisbt-plugins/SearchRelatedIssue#1]
Our mantis is located in subfolder e.g. `https://www.somesite.com/mantis` .
When creating new issue, ajax calls are called aginst
`https://www.somesite.com/plugin.php?page=SearchRelatedIssue/search`
That is incorrect. Correct endpoint is probably
`https://www.somesite.com/mantis/plugin.php?page=SearchRelatedIssue/search`

**Comment by brlumen** [comment]
@hamacekh Thanks for the feedback! I will try to fix it soon.

**Comment by brlumen** [comment]
@hamacekh Please download https://github.com/mantisbt-plugins/SearchRelatedIssue/archive/fix-ajax-calls-when-installed-in-subfolder.zip

**Comment by hamacekh** [comment]
Nice!

It is working :+1:
